name: EMCCOM
version: ${project.version}
main: net.earthmc.emccom.EMCCOM
api-version: 1.19
authors: [ Windows10Laptop, CorruptedGreed ]
description: A combat tag plugin!
depend:
  - Towny
commands:
  combattag:
    description: Assists admins in tagging and untagging users.
    permission: emccom.command.combattag
    permission-message: You do not have permission to run this command!
    usage: /combattag help