name: Core
version: 1.0
main: me.foksha.core.Core
api-version: 1.19
authors: [ Foksha & Windows10Laptop & Ludwig_H ]
description: A combat tag plugin!
depend:
  - Towny
commands:
  combattag:
    description: Assists admins in tagging and untagging users.
    permission: nebula.command.combattag
    permission-message: You do not have permission to run this command!
    usage: /combattag help